# Generated by Django 6.0.4 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='路径名称（唯一标识，同时作为磁盘文件名）')),
                ('site', models.CharField(default='default', max_length=50, verbose_name='所属站点标识（对应 .env 中的 SITE_SLUG，用于按站点筛选文章）')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图URL')),
                ('content_path', models.CharField(max_length=500, verbose_name='HTML内容文件相对路径（相对于MEDIA_ROOT）')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数（自动计算）')),
                ('reading_time', models.IntegerField(default=0, verbose_name='阅读时长/分钟（自动计算）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
    ]
